name: Deploy Latest
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
jobs:
  sync-dev-to-main:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Sync dev to main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git checkout -b ci/sync-dev-to-main origin/main
          git rebase origin/dev
          git push -u origin HEAD
          gh pr create --fill --head "ci/sync-dev-to-main" --base "main"

  release-please:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          target-branch: main
      - name: Checkout Repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.ADMIN_TOKEN }}
          fetch-depth: 0
      - name: Sync release commit to dev
        if: ${{ steps.release.outputs.release_created }}
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git checkout -b ci/cherry-pick-release-commit origin/dev
          git cherry-pick origin/main

          if [ "$?" != "0" ]; then
            git checkout --ours "${{github.workspace}}/CHANGELOG.md"
            git checkout --theirs "${{github.workspace}}/test"
            git cherry-pick --continue
          fi

          git push -u origin HEAD
          gh pr create --fill --head "ci/cherry-pick-release-commit" --base "dev"
