name: Deploy Latest
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
jobs:
  sync-dev-to-main:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Sync dev to main
        run: |
          git config --global user.email "Ben Elan"
          git config --global user.name "no-reply@benelan.dev"
          git rebase --autostash origin/dev
          git pull --rebase origin main
          git push origin main

  release-please:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          target-branch: main
      - name: Checkout Repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.ADMIN_TOKEN }}
          fetch-depth: 0
      - name: Sync release commit to dev
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config --global user.email "Ben Elan"
          git config --global user.name "no-reply@benelan.dev"

          git checkout -b ci/cherry-pick-release-commit origin/dev

          if ! git cherry-pick origin/main; then
            git checkout --ours "${{github.workspace}}/CHANGELOG.md"
            git checkout --theirs "${{github.workspace}}/test"
            git cherry-pick --continue
          fi
          gh pr create --fill --base "dev" --label "skip visual snapshots"
